openapi: 3.2.0
info:
  version: v10.40.4
  contact: {}
  title: Vic.ai Authentication API
  description: '## Introduction


    The Vic.ai API provides a seamless connection between your Enterprise Resource

    Planning (ERP) system and the Vic.ai product suite.'
servers:
- url: https://api.no.stage.vic.ai
  description: staging server, NO
- url: https://api.us.vic.ai
  description: production server, US
- url: https://api.no.vic.ai
  description: production server, NO
security:
- BearerAuth: []
tags:
- name: Authentication
  description: 'To initiate the authentication process, send a POST request to `/v0/token` with

    the payload as shown in the example below:


    ```json

    {

    "client_id": "VIC_CLIENT_ID",

    "client_secret": "VIC_CLIENT_SECRET"

    }

    ```


    Here is an example of how to do this:


    ```bash

    curl -X POST https://api.us.vic.ai/v0/token \

    -H "Content-Type: application/json" \

    -d ''{"client_id": "VIC_CLIENT_ID", "client_secret": "VIC_CLIENT_SECRET"}''

    ```


    Upon providing a valid client ID and client secret, you should receive a

    response…'
paths:
  /v0/token:
    post:
      description: Use this endpoint to obtain an access token that can be used to authenticate subsequent requests to the API.
      summary: Obtain an access token
      operationId: obtainToken
      tags:
      - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTokenInput'
      responses:
        '200':
          $ref: '#/components/responses/TokenCreatedResponse'
        4XX:
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    ErrorString:
      type: string
      maxLength: 255
    GetTokenInput:
      type: object
      required:
      - client_id
      - client_secret
      properties:
        client_id:
          type: string
        client_secret:
          type: string
    GetTokenResult:
      type: object
      required:
      - access_token
      - token_type
      - expires_in
      properties:
        access_token:
          type: string
        token_type:
          type: string
          enum:
          - Bearer
        expires_in:
          type: integer
    Error:
      description: 'generic error message in JSON format.  Note the ''code'' field should

        match the HTTP status code of the wrapping HTTP request.

        '
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
          minimum: 100
          maximum: 599
        message:
          $ref: '#/components/schemas/ErrorString'
  responses:
    ErrorResponse:
      description: An unexpected error has occurred. Check the body for more details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    TokenCreatedResponse:
      description: Successful access token request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetTokenResult'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
x-tagGroups:
- name: Integration
  tags:
  - Authentication
  - Pagination
  - Webhooks
  - Webhook Subscriptions
  - Webhook Events
  - Synchronizing
  - Status
- name: Master Data
  tags:
  - Accounts
  - Dimensions
  - Vendors
  - Vendor Groups
  - Vendor Tags
  - Tags
  - Tax Codes
  - VAT Codes
  - Payment Terms
- name: Organization & Access
  tags:
  - Partners
  - Organizations
  - Companies
  - Users
- name: Invoices & Bills
  tags:
  - Invoices
  - Bills
  - Attachments
  - Invoice Approval Flows
  - Invoice Posting Guide
  - Training Invoices
- name: Purchase Orders
  tags:
  - Purchase Orders
  - Purchase Order Line Items
  - Purchase Order Matching Guide
- name: Payments
  tags:
  - Payment Batches
  - Payment Confirmations
  - Credit Confirmations
- name: Reporting
  tags:
  - CSV Reports
- name: Reference
  tags:
  - Changelog
